[package]
name = "octant"
version = "0.2.1"
authors = ["Lazaro Alonso <lazarus.alon@gmail.com>"]
edition = "2024"
description = "An interactive viewer for n-dimensional datasets with native support for local and cloud object storage, Zarr, and Icechunk. Built in Rust with GPU-accelerated rendering."
readme = "README.md"
repository = "https://github.com/lazarusA/octant"
documentation = "https://docs.rs/octant"
license = "MIT OR Apache-2.0"
keywords = ["visualization", "zarr", "icechunk", "wgpu", "graphics"]
categories = ["visualization", "graphics", "science"]

[dependencies]
egui = "0.36"
eframe = { version = "0.36", features = ["wgpu"] }
wgpu = { version = "30", features = ["webgpu", "webgl"] }
bytemuck = { version = "1.25", features = ["derive"] }
glam = { version = "0.33", features = ["bytemuck"] }
log = "0.4"
zarrs = { version = "0.23", features = ["blosc", "async"] }
zarrs_object_store = { version = "0.7", features = ["http"] }
zarrs_icechunk = "0.5"
icechunk = "2.1.2"
object_store = { version = "0.14", features = ["http", "aws", "azure", "gcp"] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.53", features = ["full"] }
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.1"
