//! Built-in colormap catalog decoded from `assets/colormaps/colormaps.bin`
//! (generated by `cargo run --bin fetch_colormaps`).

use super::format::{self, CatalogRecords, FamilyRecord, MapRecord};
use super::kind::ColormapKind;
use super::lut::{Lut, resample, smooth};
use std::sync::LazyLock;

static CATALOG_BYTES: &[u8] = include_bytes!("../../../assets/colormaps/colormaps.bin");

/// License texts and attributions of every bundled family, shipped inside the
/// binary so the notices accompany every native and web distribution.
pub const LICENSES_TEXT: &str = include_str!("../../../assets/colormaps/LICENSES.md");

/// Provenance of a colormap family, shown in the picker and the About credits.
#[derive(Debug, Clone)]
pub struct ColormapFamily {
    pub key: String,
    pub name: String,
    pub license: String,
    pub source: String,
    pub attribution: String,
}

/// A ready-to-sample colormap.
#[derive(Debug, Clone)]
pub struct ColormapEntry {
    /// Stable identifier `"family:name"`, used for persistence.
    pub key: String,
    pub name: String,
    /// Index into [`BuiltinCatalog::families`]; `None` for user-defined maps.
    pub family: Option<usize>,
    pub kind: ColormapKind,
    pub lut: Box<Lut>,
    /// Continuous "smooth twin" of a short categorical palette (its colors
    /// blended in Oklab); `None` for continuous maps and long palettes.
    pub smooth: Option<Box<Lut>>,
}

/// Categorical palettes up to this many colors get a smooth twin. Longer ones
/// (Glasbey, Crameri's 100-color `S` palettes) are unordered, so blending them
/// would only produce noise.
pub const SMOOTH_MAX_COLORS: usize = 24;

#[derive(Debug, Default)]
pub struct BuiltinCatalog {
    pub families: Vec<ColormapFamily>,
    pub maps: Vec<ColormapEntry>,
}

static BUILTIN: LazyLock<BuiltinCatalog> = LazyLock::new(|| match format::decode(CATALOG_BYTES) {
    Ok(records) => BuiltinCatalog::from_records(records),
    Err(e) => {
        log::error!("Failed to decode bundled colormaps: {e}; falling back to grayscale");
        BuiltinCatalog::fallback()
    }
});

/// The bundled catalog, decoded once on first use.
pub fn builtin() -> &'static BuiltinCatalog {
    &BUILTIN
}

impl BuiltinCatalog {
    fn from_records(records: CatalogRecords) -> Self {
        let families: Vec<ColormapFamily> = records.families.into_iter().map(family).collect();
        let maps: Vec<ColormapEntry> = records
            .maps
            .into_iter()
            .map(|m| entry(m, &families))
            .collect();
        if maps.is_empty() {
            return Self::fallback();
        }
        Self { families, maps }
    }

    fn fallback() -> Self {
        Self {
            families: Vec::new(),
            maps: vec![ColormapEntry {
                key: "fallback:gray".into(),
                name: "gray".into(),
                family: None,
                kind: ColormapKind::Sequential,
                lut: resample(&[[0, 0, 0], [255, 255, 255]], false),
                smooth: None,
            }],
        }
    }
}

fn family(f: FamilyRecord) -> ColormapFamily {
    ColormapFamily {
        key: f.key,
        name: f.name,
        license: f.license,
        source: f.source,
        attribution: f.attribution,
    }
}

fn entry(m: MapRecord, families: &[ColormapFamily]) -> ColormapEntry {
    let family_idx = usize::from(m.family);
    let family_key = families
        .get(family_idx)
        .map_or("unknown", |f| f.key.as_str());
    ColormapEntry {
        key: format!("{family_key}:{}", m.name),
        lut: resample(&m.stops, m.kind.is_discrete()),
        smooth: (m.kind.is_discrete() && (2..=SMOOTH_MAX_COLORS).contains(&m.stops.len()))
            .then(|| smooth(&m.stops)),
        name: m.name,
        family: Some(family_idx),
        kind: m.kind,
    }
}
