//! Coastline vertex data at three levels of detail.
//!
//! # Format
//!
//! All coastline buffers are flat sequences of `f32` pairs `[lon, lat]` in WGS-84
//! geographic coordinates (degrees, −180..180 / −90..90). Adjacent line-string
//! segments are separated by a sentinel pair `[f32::NAN, f32::NAN]`.
//!
//! # Data source
//!
//! Natural Earth vector data — <https://www.naturalearthdata.com>
//! Public domain. No attribution required.
//!
//! Binary files are generated by `cargo run --bin fetch_coastlines` and committed
//! to `assets/coastlines/`. The 110m level is embedded directly into the binary
//! via `include_bytes!` for zero-cost availability on all platforms including WASM.
//! Coarser levels are loaded from the user cache or downloaded on native builds.

use bytemuck::cast_slice;

// Force 4-byte alignment on the embedded byte blob so bytemuck::cast_slice
// can safely reinterpret it as &[f32] without panicking.
#[repr(C, align(4))]
struct Aligned4<T: ?Sized>(T);

/// Coastline level of detail.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoastlineLod {
    /// 1:110 000 000 — ~5 K vertex pairs, 41 KB. Suitable for world-scale views.
    Lod110m,
    /// 1:50 000 000 — ~60 K vertex pairs, 483 KB. Good for continental views.
    Lod50m,
    /// 1:10 000 000 — ~411 K vertex pairs, 3.2 MB. Regional / zoomed-in views.
    Lod10m,
}

impl CoastlineLod {
    /// Chooses the appropriate LOD based on the current zoom level.
    ///
    /// `zoom` is the same scalar used in `PlotRenderParams::zoom`
    /// (1.0 = world fits the canvas, higher = zoomed in).
    pub fn from_zoom(zoom: f32) -> Self {
        if zoom < 4.0 {
            Self::Lod110m
        } else if zoom < 20.0 {
            Self::Lod50m
        } else {
            Self::Lod10m
        }
    }
}

// ---------------------------------------------------------------------------
// 110 m — statically embedded (41 KB, works on WASM)
// ---------------------------------------------------------------------------

/// 110m coastline vertices embedded at compile time.
///
/// Returns a `&'static [f32]` slice of interleaved `[lon, lat]` pairs.
/// Segments are separated by `[NaN, NaN]` sentinels.
pub fn coastline_110m_static() -> &'static [f32] {
    // The Aligned4 wrapper guarantees the byte slice has at least 4-byte
    // alignment, which bytemuck requires before it will cast &[u8] → &[f32].
    static ALIGNED: &Aligned4<[u8]> = &Aligned4(*include_bytes!(
        "../../assets/coastlines/coastline_110m.bin"
    ));
    cast_slice(&ALIGNED.0)
}

// ---------------------------------------------------------------------------
// 50 m and 10 m — loaded from disk (native only)
// ---------------------------------------------------------------------------

const COASTLINE_REPOSITORY_URL: &str =
    "https://raw.githubusercontent.com/lazarusA/octant/main/assets/coastlines";

/// Loads the 50m or 10m coastline from the local cache, development assets, or repository.
///
/// Missing files are downloaded into the platform's user cache directory.
#[cfg(not(target_arch = "wasm32"))]
pub fn load_coastline_from_disk(lod: CoastlineLod) -> Option<Vec<f32>> {
    let filename = match lod {
        CoastlineLod::Lod110m => "coastline_110m.bin",
        CoastlineLod::Lod50m => "coastline_50m.bin",
        CoastlineLod::Lod10m => "coastline_10m.bin",
    };

    let mut candidates = Vec::with_capacity(3);
    if let Some(cache_dir) = coastline_cache_dir() {
        candidates.push(cache_dir.join(filename));
    }
    candidates.push(std::path::PathBuf::from("assets/coastlines").join(filename));
    if let Ok(executable) = std::env::current_exe()
        && let Some(parent) = executable.parent()
    {
        candidates.push(parent.join("assets/coastlines").join(filename));
    }

    for path in &candidates {
        if let Ok(bytes) = std::fs::read(path) {
            if bytes.len() % (std::mem::size_of::<f32>() * 2) == 0 {
                // Use pod_collect_to_vec: copies u8 → f32 safely regardless
                // of the Vec<u8> allocator alignment.
                let floats: Vec<f32> = bytemuck::pod_collect_to_vec(&bytes);
                return Some(floats);
            }
            log::warn!(
                "coastline file '{}' has unexpected byte length {}; skipping",
                path.display(),
                bytes.len(),
            );
        }
    }

    let cache_dir = coastline_cache_dir()?;
    if let Err(error) = std::fs::create_dir_all(&cache_dir) {
        log::warn!(
            "Unable to create coastline cache '{}': {error}",
            cache_dir.display()
        );
        return None;
    }

    let url = format!("{COASTLINE_REPOSITORY_URL}/{filename}");
    let response = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(60))
        .build()
        .ok()?
        .get(url)
        .send()
        .ok()?
        .error_for_status()
        .ok()?;
    let bytes = response.bytes().ok()?;
    if !valid_coastline_bytes(&bytes) {
        log::warn!("Downloaded coastline file '{filename}' has invalid contents");
        return None;
    }

    let cache_path = cache_dir.join(filename);
    let temporary_path = cache_path.with_extension("bin.download");
    if let Err(error) = std::fs::write(&temporary_path, &bytes) {
        log::warn!(
            "Unable to write coastline cache '{}': {error}",
            temporary_path.display()
        );
        return None;
    }
    if let Err(error) = std::fs::rename(&temporary_path, &cache_path) {
        let _ = std::fs::remove_file(&temporary_path);
        log::warn!(
            "Unable to install coastline cache '{}': {error}",
            cache_path.display()
        );
        return None;
    }

    Some(bytemuck::pod_collect_to_vec(&bytes))
}

#[cfg(not(target_arch = "wasm32"))]
fn coastline_cache_dir() -> Option<std::path::PathBuf> {
    if let Ok(cache_root) = std::env::var("XDG_CACHE_HOME")
        && !cache_root.is_empty()
    {
        return Some(std::path::PathBuf::from(cache_root).join("octant/coastlines"));
    }

    #[cfg(target_os = "macos")]
    if let Ok(home) = std::env::var("HOME") {
        return Some(std::path::PathBuf::from(home).join("Library/Caches/Octant/coastlines"));
    }

    #[cfg(target_os = "windows")]
    if let Ok(local_app_data) = std::env::var("LOCALAPPDATA") {
        return Some(std::path::PathBuf::from(local_app_data).join("Octant/coastlines"));
    }

    std::env::var_os("HOME")
        .map(|home| std::path::PathBuf::from(home).join(".cache/octant/coastlines"))
}

#[cfg(not(target_arch = "wasm32"))]
fn valid_coastline_bytes(bytes: &[u8]) -> bool {
    bytes.len() >= 8 && bytes.len().is_multiple_of(std::mem::size_of::<f32>() * 2)
}

/// Returns the best available coastline for the requested LOD.
///
/// Falls back to the embedded 110m data if the requested file is missing.
/// On WASM only 110m is ever available.
pub fn load_coastline(lod: CoastlineLod) -> CoastlineBuffer {
    match lod {
        CoastlineLod::Lod110m => CoastlineBuffer::Static(coastline_110m_static()),
        #[cfg(not(target_arch = "wasm32"))]
        CoastlineLod::Lod50m | CoastlineLod::Lod10m => match load_coastline_from_disk(lod) {
            Some(v) => CoastlineBuffer::Owned(v),
            None => {
                log::warn!("Falling back to embedded 110m coastline.");
                CoastlineBuffer::Static(coastline_110m_static())
            }
        },
        #[cfg(target_arch = "wasm32")]
        CoastlineLod::Lod50m | CoastlineLod::Lod10m => {
            log::warn!("50m/10m coastlines unavailable on WASM; using 110m.");
            CoastlineBuffer::Static(coastline_110m_static())
        }
    }
}

// ---------------------------------------------------------------------------
// Buffer wrapper
// ---------------------------------------------------------------------------

/// Holds coastline vertex data, either borrowed from a static or owned on heap.
pub enum CoastlineBuffer {
    /// Points into the `'static` embedded binary — zero allocation.
    Static(&'static [f32]),
    /// Heap-allocated data loaded from disk.
    Owned(Vec<f32>),
}

impl CoastlineBuffer {
    /// Returns a slice of `[lon, lat]` `f32` pairs.
    pub fn as_slice(&self) -> &[f32] {
        match self {
            Self::Static(s) => s,
            Self::Owned(v) => v.as_slice(),
        }
    }
}

/// Expands separated paths into explicit GPU line-list pairs.
pub fn expand_coastline_line_list(vertices: &[f32]) -> Vec<f32> {
    let mut expanded = Vec::with_capacity(vertices.len().saturating_mul(2));
    let mut previous: Option<(f32, f32)> = None;
    for pair in vertices.chunks_exact(2) {
        let point = (pair[0], pair[1]);
        if !point.0.is_finite() || !point.1.is_finite() {
            previous = None;
            continue;
        }
        if let Some(last) = previous {
            expanded.extend_from_slice(&[last.0, last.1, point.0, point.1]);
        }
        previous = Some(point);
    }
    expanded
}

// ---------------------------------------------------------------------------
// Coordinate-alignment helpers
// ---------------------------------------------------------------------------

/// Extracts the dataset's geographic bounds from a [`crate::data::CoordinateGrid`]
/// as `(lon_min, lon_max, lat_min, lat_max)` in degrees.
///
/// # Canonical ordering
///
/// The heatmap renderer always calls `check_and_orient_axes_with_coords` before
/// uploading data to the GPU, which ensures:
/// - Row 0 = North (NDC y = +1)
/// - Col 0 = West  (NDC x = -1)
///
/// Therefore the coastline shader only needs the **geographic min/max** —
/// storage direction (ascending vs descending) has already been handled.
/// The returned values always satisfy `lon_min ≤ lon_max` and `lat_min ≤ lat_max`.
///
/// Falls back to global defaults `(-180, 180, -90, 90)` when the grid
/// carries no spatial coordinate information.
pub fn dataset_geo_bounds(grid: &crate::data::CoordinateGrid) -> (f32, f32, f32, f32) {
    use crate::data::CoordinateGrid;

    match grid {
        CoordinateGrid::GlobalRegular => {
            // Full global extent — standard plate carrée.
            (-180.0, 180.0, -90.0, 90.0)
        }

        CoordinateGrid::RegionalRegular {
            lon_bounds,
            lat_bounds,
        } => {
            // Detection already stores these as (min, max).
            let (lon_min, lon_max) = *lon_bounds;
            let (lat_min, lat_max) = *lat_bounds;
            (lon_min, lon_max, lat_min, lat_max)
        }

        CoordinateGrid::Irregular1D {
            coords_x,
            coords_y,
            lon_bounds,
            lat_bounds,
        } => {
            // `lon_bounds` / `lat_bounds` store (min, max) as set by detect_grid.
            // Prefer them over first/last coord so a descending axis (e.g. 180→-180)
            // still yields the correct geographic extent.
            let _ = (coords_x, coords_y); // bounds carry what we need
            let (lon_min, lon_max) = *lon_bounds;
            let (lat_min, lat_max) = *lat_bounds;
            (lon_min, lon_max, lat_min, lat_max)
        }

        CoordinateGrid::Curvilinear2D {
            lon_bounds,
            lat_bounds,
            ..
        } => {
            let (lon_min, lon_max) = *lon_bounds;
            let (lat_min, lat_max) = *lat_bounds;
            (lon_min, lon_max, lat_min, lat_max)
        }
    }
}
